// This file was autogenerated by some hot garbage in the `nimbus-fml` crate.
// Trust me, you don't want to mess with it!

public func helloWorld() {
     print("Hello World!")
 }

public func mult(a: Int, b: Int) -> Int {
    return a * b
}