// This file was autogenerated by some hot garbage in the `nimbus-fml` crate.
// Trust me, you don't want to mess with it!

// This file was autogenerated by some hot garbage in the `nimbus-fml` crate.
// Trust me, you don't want to mess with it!

{%- for imported_module in self.imports() %}
import {{ imported_module }}
{%- endfor %}

{% let nimbus_object = self.config.nimbus_object_name() -%}
///
/// An object for safely accessing feature configuration from Nimbus.
///
/// This is generated.
public struct {{ nimbus_object }}Struct {
    ///
    /// This should be populated at app launch.
    ///
    public var api: FeaturesInterface? = nil

    public let features = Features()
}

public var {{ nimbus_object }} = {{ nimbus_object }}Struct()

public class Features {
    {%- for f in self.iter_feature_defs() %}
    {%- let raw_name = f.name() %}
    {%- let class_name = raw_name|class_name %}
    {{ f.doc()|comment("        ") }}
    public lazy var {{raw_name|var_name}}: FeatureHolder<{{class_name}}> = {
        FeatureHolder({ {{ nimbus_object }}.api }, {{ raw_name|quoted }}) { (variables) in
            {{ class_name }}(variables)
        }
    }()
    {%- endfor %}
}


{%- for code in self.initialization_code() %}
{{ code }}
{%- endfor %}

// Public interface members begin here.
{% for code in self.declaration_code() %}
{{- code }}
{%- endfor %}

{% import "macros.kt" as kt %}