apply from: "$appServicesRootDir/build-scripts/component-common.gradle"
apply from: "$publishDir/publish.gradle"

android {
    namespace 'org.mozilla.appservices.search'
}

dependencies {
    api project(":remotesettings")
}

ext.configureUniFFIBindgen("search")
ext.dependsOnTheMegazord()
ext.configurePublish(appServicesGroupId, project.name, project.ext.description)