/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/. */

@file:Suppress("ClassName", "InvalidPackageDeclaration", "ktlint:standard:filename", "MatchingDeclarationName")

package com.example.app
/**
 * This is a fake resources of (R.java) file; it is normally generated by aapt as part of the Android
 * build process.
 *
 * This particular file contains references mentioned in the testing yaml files.
 */
object R {
    object string {
        const val app_menu_settings_punctuation = 1
        const val app_menu_settings_title = 2
        const val dx_label = 3
        const val foo_text = 4
        const val bar_text = 5
        const val my_scalar_text = 5
        const val my_optional_text = 6
    }

    object drawable {
        const val mozac_ic_settings = 1
        const val foo_image = 2
        const val bar_image = 3
        const val my_optional_image = 4
        const val my_single_image = 5
    }
}
