/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package com.example.lib
/**
 * This is a fake resources of (R.java) file; it is normally generated by aapt as part of the Android
 * build process.
 *
 * This particular file contains references mentioned in the testing yaml files.
 */
@Suppress("ClassNaming")
object R {

    object string {

    }

    object drawable {

    }
}
