[package]
name = "error-support"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"
autotests = false
exclude = ["/android"]

[dependencies]
backtrace = { version = "0.3", optional = true}
error-support-macros = { path = "macros" }
env_logger = { version = "0.10", default-features = false }
glean = { version = "70", optional = true }
glean-sym = { version = "70", optional = true }
lazy_static = { version = "1.4" }
log = { version = "0.4" }
parking_lot = { version = ">=0.11,<=0.12" }
tracing-support = { path = "../tracing" }
uniffi = { version = "0.32" }

[build-dependencies]
uniffi = { version = "0.32", features=["build"]}
glean-build = { git = "https://github.com/mozilla/glean", tag = "v70.0.0" }

[features]
backtrace = ["dep:backtrace"]
testing = []
# Should we use glean-sym to report the error ping?
# This is a temporary flag so that we can introduce the new system one application at a time.
glean-sym = ["dep:glean-sym"]
# Use Firefox-on-Glean to publish metrics (Desktop)
# Note: if set, we will not use `glean-sym`
glean-fog = ["dep:glean"]
